version: '3.9'
services:
  web:
    image: srv-iam:latest
    networks:
      - schambeck-net
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/iam
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 256M
  db:
    image: 'mysql'
    networks:
      schambeck-net:
        aliases:
          - db
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=iam
networks:
  schambeck-net:
    driver: bridge
